predator fs done. Different pin for the observations
mchyll/sausee pull request #152
Opened 2021-02-23 10:20 UTC by Trulsmatias

2021-02-24 13:12 UTC, mchyll commented on screens/PredatorFormScreen.tsx
> +            props.setPredatorSpecies(itemValue.toString());
var det en spesiell grunn til at du bruker toString på itemValue? Ser at den allerede er en string

2021-02-24 13:44 UTC, Trulsmatias commented on screens/PredatorFormScreen.tsx
> +            props.setPredatorSpecies(itemValue.toString());
nei 🥸 fjernet nå

2021-02-24 13:45 UTC, mchyll requested changes
Nice!

Fant noen issues:
- Dropdownen er litt for smal på Android, sånn at flere av navnene truncates. Se bildene på punktet under
- Tastaturet havner over både nummerfeltet og tekstfeltet for Annet rovdyr, slik at jeg ikke ser hva jeg skriver: https://www.jottacloud.com/share/vncd3bpfj3tv og https://www.jottacloud.com/share/cm1o737o9v6u
- Hvis jeg visker ut sifrene i nummerfeltet får jeg NaN: https://www.jottacloud.com/share/5bhl8v9kv7pe Dette står fortsatt etter jeg lagrer og går inn på observasjonen igjen
- Litt vanskelig å komme seg ut av redigering i feltene/lukke tastaturet. På Android kan jeg bruke back-button, og på iPhone kan jeg bruke Return-knappen, men den finnes ikke i nummertastaturet. Intuitivt forventer jeg at trykk andre steder på skjermen vil lukke dem, men det funker ikke: https://www.jottacloud.com/share/fetpr3m33alo

2021-02-24 13:56 UTC, mchyll commented on screens/PredatorFormScreen.tsx
> +            props.setPredatorSpecies(itemValue.toString());
Aha 🐱‍🏍

2021-02-24 15:10 UTC, Trulsmatias commented
blir unblur på tekstfeltet kalt når man trykker utenfor?

2021-03-01 09:34 UTC, Trulsmatias commented
Pointer event on dropdown on android is not fixed.
flytte margen-sjekken til slett observasjonsknappen til element i rovdyr fs
gjøre rovdyr fs om til et scrollview. Funker fortsatt pickeren på iOS da?

2021-03-02 13:25 UTC, mchyll commented
- Scrolles til toppen når man trykker inn i tekstfeltene, slik at de havner bak tastaturet
- Predator species overskrives og settes til Annet når man lukker FS vha å swipe den ned

2021-03-02 14:47 UTC, mchyll requested changes

2021-03-02 14:47 UTC, mchyll commented on screens/FormScreenFrame.tsx
> +      {Platform.OS === "ios" && <View style={{ height: 300 }}></View>}
Sjekk shouldFinishObservation, siden boksen ikke trenger å vises i andre formScreens enn predator

2021-03-03 07:49 UTC, mchyll approved these changes
YES

2021-03-03 07:49 UTC, merged