new way of ending trip
mchyll/sausee pull request #97
Opened 2021-01-20 14:39 UTC by Trulsmatias

2021-01-26 10:13 UTC, mchyll requested changes

2021-01-26 10:13 UTC, mchyll commented on App.tsx
> +                headerTitle: "Sett saueposisjon",
🐛 Tittelen vises ikke lengre på Android

2021-01-26 10:13 UTC, mchyll commented on App.tsx
> +                  onPress={() => {
Jeg synes vi bør ha med "Vil du avslutte turen?"-dialogboksen, sånn som det er i dagens løsning

2021-01-26 13:46 UTC, Trulsmatias commented on App.tsx
> +                  onPress={() => {
Done

2021-01-29 14:18 UTC, mchyll commented
@Trulsmatias Jeg fiksa TMS-tittel-bugen på Android i denne PRen, men den var opprinnelig blocked av at background tracking ikke funka lengre, så jeg la inn en workaround for det som tracker i forgrunnen. Det er derfor med i denne PRen, så ta gjerne en titt på de endringene om du vil: https://github.com/mchyll/sausee/pull/97/commits/656da9578482950480c25378e41f904f093253ef

2021-01-29 14:20 UTC, mchyll approved these changes

2021-01-29 14:28 UTC, Trulsmatias commented
> @Trulsmatias Jeg fiksa TMS-tittel-bugen på Android i denne PRen, men den var opprinnelig blocked av at background tracking ikke funka lengre, så jeg la inn en workaround på det som tracker i forgrunnen isteden. Det er derfor med i denne PRen, så ta gjerne en titt på de endringene om du vil: [656da95](https://github.com/mchyll/sausee/commit/656da9578482950480c25378e41f904f093253ef)

Nice link til commit 👀

2021-01-29 14:35 UTC, Trulsmatias reviewed
🔟/🔟

2021-01-29 14:35 UTC, merged